### ISSUE TITLE
เพิ่มยอดคนลงชื่อ ในส่วนLanding

### ISSUE THREAD

**Issue by namsaisup** [wevisdemo/conforall#21]
<img width="297" alt="CleanShot 2566-08-18 at 11 01 01@2x" src="https://github.com/wevisdemo/conforall/assets/123941533/7f8053ad-9745-4fb4-8595-ce99f4b38af4">

**Comment by Th1nkK1D** [comment]
```
value = firestoreCount + offlineConstance - expectedSpam
```

**Comment by Th1nkK1D** [comment]
@namsaisup ตรง update timestamp อะครับ ไม่รู้ว่าควรใช้เลขไหน ในเมื่อ online มันนับ realtime แต่ว่า offline manual วันละครั้ง หรือว่าไม่ต้องใส่เวลาก็ได้เพราะเป็นการ underestimate อยู่แล้ว

**Comment by Th1nkK1D** [comment]
> @namsaisup ตรง update timestamp อะครับ ไม่รู้ว่าควรใช้เลขไหน ในเมื่อ online มันนับ realtime แต่ว่า offline manual วันละครั้ง หรือว่าไม่ต้องใส่เวลาก็ได้เพราะเป็นการ underestimate อยู่แล้ว

ผมตัดสินใจละว่าแบบนี้ละกันจำนวน online จะ update ทุกครั้งที่ build (นั่นคือเมื่อแก้ code หรือ update จำนวน offline) แล้วก็ใช้ timestamp ในจังหวะนั้นแหละ
