### ISSUE TITLE
feat(landing): green section

### ISSUE THREAD

**Issue by Th1nkK1D** [wevisdemo/conforall#3]
![image](https://github.com/wevisdemo/conforall/assets/8860448/de0aa24f-d58b-4d8e-bf96-570a3a3868ee)

**Comment by Th1nkK1D** [comment]
ตอนนี้ design ไม่ได้ทำ isSubmitting state (กดแล้วกำลังยิง Firebase) กับ success state ไว้ คิดว่าควร implement ui แบบเร็วๆ อย่างน้อยให้ user รู้ว่าอยู่ state ไหน (และถ้ามีเวลา error state ก็ดี)

ตอนนี้ form ใช้ lib [felte](https://felte.dev/docs/svelte/getting-started) ช่วย ซึ่ง createForm return isSubmitting ที่อาจจะใช้ได้ แต่ตอนส่งสำเร็จไม่มั่นใจว่าใช้ท่าไหนดี

**Comment by mixth** [comment]
@Th1nkK1D ผม handle ง่ายๆแบบนี้ไปนะครับ 

#### ตอนกดส่ง (disabled ทุก input)
![Screenshot 2023-08-13 at 3 55 47 AM](https://github.com/wevisdemo/conforall/assets/6439183/b2dfb35d-76cc-4ebf-bc1c-604cf2fe827f)

#### ตอน error
![Screenshot 2023-08-13 at 3 55 59 AM](https://github.com/wevisdemo/conforall/assets/6439183/2c28ecf5-d0b2-4b7d-bca2-7b76ad21fc8c)

ปล. ใช้ boolean ง่ายๆไปครับ อ่าน felte ไม่ทัน
